server:
  port: 8099

spring:
  datasource:
      url: jdbc:mysql://localhost:3306/bgm?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: root


mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml
